### ISSUE TITLE
Nav bar stays hidden when switching from small viewport to large viewport

### ISSUE THREAD

**Issue by tlwirtz** [patSSFC/portfolio-seattle301n2-remix#2]
When your site viewed on a mobile viewport, you have a nice hamburger menu the shows/hides your nave menu. If your nav menu is closed, and you increase the viewport, the hamburger menu goes away but your nav bar does not appear. 
Might need to add a break point that automatically changes the CSS `display` property from `none`

**Comment by patSSFC** [comment]
Look up window.onresize and create a function that listens for a window resize and then appliies the correct display style.
